# Generated by Django 4.2.3 on 2023-07-31 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_level2_projectstatus_taskstatus_team_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'priorities',
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'project_types',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrumboard.priority'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrumboard.projecttype'),
        ),
    ]
