# Generated by Django 4.2.3 on 2023-07-31 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0003_priority_projecttype_alter_projects_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrumboard.projects')),
            ],
            options={
                'db_table': 'project_timelines',
            },
        ),
    ]
