# Generated by Django 4.2.3 on 2023-07-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0005_projecttimeline_created_on_projecttimeline_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='progress',
        ),
    ]
