# Generated by Django 4.2.3 on 2023-08-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0006_rename_status_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comment',
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrumboard.task')),
            ],
            options={
                'db_table': 'task_comments',
            },
        ),
    ]
