# Generated by Django 4.2.3 on 2023-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0009_userteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
